const suffixList = [
		["ach", "a", "aa", "ah"],
		["ar", "ahr"],
		["ate", "te", "nit", "net"],
		["au", "aue", "oog", "ooge", "ohe", "oie"],
		["bach", "bach", "bek", "beken", "beck", "bke"],
		["berg", "bergen", "barg", "bargen"],
		["born", "bronn"],
		["bruch", "broich", "brook", "brock", "brauk"],
		["bruck", "brück", "brügge"],
		["burg", "borg"],
		["bühl", "bühel", "bihl", "beuel", "bichel", "pichl"],
		["büttel"],
		["dorf", "torf", "troff", "druf", "dorp", "dörp", "torp", "trop", "trup", "torf", "torp", "trup"],
		["ede", "de", "da", "te", "ta", "t"],
		["feld", "felde"],
		["furt", "furt", "furth", "fürth", "ford", "fort", "vörde"],
		["graben"],
		["hag", "hagen",  "haag", "hain", "han", "hahn"],
		["hau"],
		["hausen", "haus", "husen"],
		["heim", "heimen",  "ham", "am", "hem", "em", "um"],
		["hof", "hofen", "höfen", "hoven"],
		["horn", "hörn"],
		["horst", "host", "ost", "hurst"],
		["hoven"],
		["ich"],
		["in"],
		["ing", "ingen", "ung", "ungen", "ens"],
		["inghausen", "iehausen", "kausen", "ingheim", "igheim", "ingem", "inghoven", "ikofen", "ikon", "iken", "ingerode"],
		["itz", "itsch", "witz", "schütz", "ütz"],
		["kirch", "kirchen", "kark", "kerk", "kerken"],
		["leben", "legen", "lehen"],
		["leiten", "leithen"],
		["loh", "lah", "loch", "loy"],
		["mar"],
		["ow"],
		["rod", "roda", "rodt", "rode", "raht", "rath", "rade", "reut", "reuth", "reute", "ried", "ruit", "ray"],
		["scheid"],
		["siefen", "seifen"],
		["siel"],
		["stadt", "stadt", "statt", "stätt", "stetten",  "städt", "stedt", "stede", "steden"],
		["stein"],
		["tal", "thal"],
		["torf"],
		["um"],
		["up"],
		["wald", "walde"],
		["weg"],
		["weiler", "weier", "weiher", "wil", "wyl", "wyhl", "viller"],
		["werder", "werth"],
		["winkel"],
		["zell"]
	];
